version: '4'
services:
  apache:
    build: .docker/apache
    container_name: popp_apache
    restart: unless-stopped
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ./apps/popp:/home/www/popp
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST} # used with https-portal
    depends_on:
      - php
    networks:
      - internal
      - gateway

  php:
    build: .docker/php
    container_name: popp_php
    restart: unless-stopped
    volumes:
      - ./apps/popp/:/home/www/popp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    networks:
      - internal
        
  postgres:
    container_name: popp_postgres
    image: postgres:13.1-alpine
    restart: unless-stopped
    env_file:
      - ./apps/popp/.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - internal
  
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: adminer.${VIRTUAL_HOST} # used with https-portal
    networks:
      - internal
      - gateway

volumes:
  postgres-data: # named volumes can be managed easier using docker-compose

networks:
  gateway:
    name: ${FRONTEND_NETWORK}

  internal:
    name: ${BACKEND_NETWORK}